name: Release for Windows

on: workflow_dispatch

jobs:
  release:
    permissions: write-all
    runs-on: macos-12
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.9.4'
          target: 'desktop'
          arch: 'clang_64'
          tools: 'tools_ifw'
          cache: true

      - name: Add QtInstallerFramework to PATH
        run: find $IQTA_TOOLS/QtInstallerFramework -name bin >> $GITHUB_PATH

      - name: Install automake
        run: brew install automake

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Build Visual Statistics
        run: |
          qmake ActionTest.pro
          make qmake_all
          make
